#!/bin/sh

# monitors=($(xrandr --query | awk '/connected/ && /[[:digit:]]x[[:digit:]].*+/{print $1}'))

# desktops=(
#     1
#     2
#     3
#     4
#     5
# )
# nb_monitors=${#monitors[@]}
# nb_desktops=${#desktops[@]}
# (( limit=(nb_desktops+nb_monitors-1)/nb_monitors ))

# for i in "${!monitors[@]}"; do
#     ((offset=i*limit))
#     subset=${desktops[@]:$offset:$limit}
#     bspc monitor ${monitors[$i]} -d $subset
#     ((i=i+1))
# done

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true


# Set monitor order
bspc wm -O ${monitors[@]}

bspc config border_width         3
bspc config borderless_monocle   false

bspc config window_gap            10
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
# Don’t replay the click that makes a window focused if click_to_focus isn’t none.
bspc config swallow_first_click true

# permit to focus with btn1 & btn3
bspc config click_to_focus any

# Floating rules {{{
bspc rule -a Nm-connection-editor state=floating
bspc rule -a \*:\*:feh_quicklook state=floating
bspc rule -a Arandr state=floting
bspc rule -a flameshot state=floating
bspc rule -a 1Password state=floating
# }}}

# Fix for Java app not working correctly.
# See here https://wiki.archlinux.org/index.php/bspwm#Problems_with_Java_applications
wmname LG3D

#bspc config focused_border_color "#BF616A"
#bspc config normal_border_color "#353b45"

# autostart up applications 
source ~/.config/bspwm/scripts/autostart.sh