- name: Install docker
  become: true
  pacman:
    name: docker
    state: present
  tags:
    - docker

- name: Install docker-compose
  become: true
  pacman:
    name: docker-compose
    state: present
  tags:
    - docker

- name: Enable docker.service
  become: true
  command: systemctl enable docker
  tags:
    - docker

- name: Add user to docker group
  become: true
  user: name={{user.name}} groups=docker append=yes
  tags:
    - docker
