- name: Import 1password signing key
  shell: |
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import
  tags:
    - 1password

- name: Cloning 1password application
  git:
    repo: https://aur.archlinux.org/1password.git
    dest: "~/aur/1password"
    clone: true
    update: true
  tags:
    - 1password

- name: Installing 1password application
  shell: |
    cd "{{dotfiles_user_home}}/{{aur.dir}}/1password"
    makepkg -si --noconfirm --needed
  tags:
    - 1password